### PR TITLE
Rename mjs to js

### PR DESCRIPTION
**Pull request by ValentinH**
.mjs extension are not supported properly by the Webpack tools.

### CODE REVIEW

**Comment by aricart** [comment]
perhaps the right thing to do is to make the cjs files cjs? https://webpack.js.org/guides/ecma-script-modules/#flagging-modules-as-esm

**Comment by ValentinH** [comment]
I tried this first but it wasn't enough.
In the end, Next still loads the mjs file for the client part. And the tool I use to transpile nats.ws breaks when using `mjs`.

I also tried using the `"type": "module"` property on the `package.json` of nats.ws but it was worse.
Only renaming `mjs` to `js` did the job.

If you don't like the name is used `.es.js` I'm fine with naming it to .js and rename the common JS version.
However, when using the `.cjs` extension I had other errors saying that it was trying to import esm modules 🤔

**Comment by ValentinH** [comment]
I tried again and have it working in Next when using `nats.cjs` for the CommonJS version and `nats.js` for the ESM version. I like it better as it acts like the default/standard one is the ESM version.

**Review by aricart — APPROVED** [review]
LGTM - need to verify that the bundling steps are doing the right thing, and that the tests work, but I can do that in the other PR.

**Pull request merged**
